version: '3'
services:
  web:
    command: >
      sh -c "bundle exec rake db:migrate && rails server -b 0.0.0.0"
    image: your-rails-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/realyou_test
    depends_on:
      postgres:
        condition: service_healthy  # Wait until postgres is healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realyou_test
    ports:
      - "5432:5432"  # Change to avoid port conflicts on the host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
