
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

development:
  <<: *default
  database: realyou_development


test:
  <<: *default
  database: realyou_test

production:
  <<: *default
  database: realyou_production
