# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      run: |
        sudo chmod -R 777 /opt/hostedtoolcache
        sudo chown -R $USER /opt/hostedtoolcache
      # Separate step for setting up Ruby using the action
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2 

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Database setup
      run: |
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:schema:load RAILS_ENV=test

    - name: Run tests
      run: |
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        bundle exec rails test
