name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realyou_test
        ports:
          - "5433:5432"  # Using port 5433 to avoid conflicts
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libpq-dev \
          nodejs \
          yarn \
          docker-ce \
          docker-compose

    - name: Build Docker image
      run: docker-compose build

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d  # Build and start containers in detached mode
        docker-compose exec web bundle exec rspec  # Run tests inside web container
        