# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realyou_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2 # Change it to your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Database setup
      run: |
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:schema:load RAILS_ENV=test

    - name: Run tests
      run: |
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        bundle exec rails test
